### ISSUE TITLE
No such group or event: TextChangedP

### ISSUE THREAD

**Issue by Tumetsu** [skywind3000/vim-keysound#2]
When issuing command `:KeysoundEnable` on Vim 8.0 on Ubuntu 18.04. 
Got sounds to work ok by going to `plugin/keysound.vim`and commenting away the line:
`au TextChangedP * call s:event_text_changed()`

Decided to not make a PR though since I don't really know enough of Vim-scripting and the said event to confidently fix this. I suppose you could add a conditional exist check for this line?

**Comment by skywind3000** [comment]
I need find a way to detect this, could you run the two following commands for me in your vim, and feed me back ?

```VimL
:echo exists('#TextChangedP')
:echo exists('#TextChangedI')
```

**Comment by Tumetsu** [comment]
Sure, those printed 0 for `:echo exists('#TextChangedP')` and 1 for `:echo exists('#TextChangedI')`

**Comment by skywind3000** [comment]
Fixed, you can try the latest version now.

**Comment by Tumetsu** [comment]
> Error detected while processing function <SNR>45_keysound_init:
> line   21:
> E216: No such group or event: TextChangedP * call s:event_text_changed()

The reason being that the if-condition is wrong way around. I made a pull request for you: https://github.com/skywind3000/vim-keysound/pull/3 

Check if it works on your Vim and merge if it does :)

**Comment by skywind3000** [comment]
Merged, thanks
