### ISSUE TITLE
macOS Mojave 10.14.5无法使用

### ISSUE THREAD

**Issue by endinferno** [skywind3000/vim-keysound#8]
# 系统环境
macOS Mojave 10.14.5

# vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 18 2019 20:13:57)
macOS version
包含补丁: 1-1550
编译者 Homebrew
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
         $VIM 预设值: "/usr/local/share/vim"
编译方式: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
链接方式: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6 

## 插件管理器为vim-plug

# 我做了什么
1. 已经安装了pysdl2和sdl2
    * pip3 install pysdl2
    * brew install  sdl2

# vim打开文件报错

处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
Traceback (most recent call last):
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sdl2/sdlmixer.py", line 54, in <module>
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sdl2/dll.py", line 54, in __init__
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
    (libinfo, dllmsg))
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
RuntimeError: could not find any library for SDL2_mixer (PYSDL2_DLL_PATH: unset)
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
During handling of the above exception, another exception occurred:
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
Traceback (most recent call last):
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
  File "<string>", line 1, in <module>
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
  File "/Users/endinferno/.vim/plugged/vim-keysound/autoload/keysound.py", line 17, in <module>
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
    import sdl2.sdlmixer
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sdl2/sdlmixer.py", line 56, in <module>
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
    raise ImportError(exc)
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[1]..<SNR>85_init[5]..<SNR>85_python 时发生错误:
第    1 行:
ImportError: could not find any library for SDL2_mixer (PYSDL2_DLL_PATH: unset)
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[4]..<SNR>85_python 时发生错误:
第    1 行:
Traceback (most recent call last):
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[4]..<SNR>85_python 时发生错误:
第    1 行:
  File "<string>", line 1, in <module>
请按 ENTER 或其它命令继续
处理 function <SNR>42_event_vim_enter[2]..<SNR>42_keysound_init[6]..keysound#init[4]..<SNR>85_python 时发生错误:
第    1 行:
NameError: name 'keysound' is not defined

**Comment by endinferno** [comment]
我好像发现了，好像是因为我的vim版本中的sound特性没有打开。

**Comment by skywind3000** [comment]
不是，不需要 vim 的sound 特性，这是 python 操纵 sdl 播放声音的。

**Comment by endinferno** [comment]
我的问题依旧没有解决，不知道您有什么解决方法吗？

**Comment by skywind3000** [comment]
你没有按照要求正常安装 PySDL 和 sdl_mixer 啊

**Comment by endinferno** [comment]
我已经安装了，但是依旧不行呢。我是按照您的Requirements来安装的。

**Comment by endinferno** [comment]
发现还需要安装一个SDL2_mixer然后就可以使用了，谢谢解答🙏
